jobs:
  include:
    - os: linux
      language: python
      python:
       - "3.8"
      cache:
        bundler: true
        directories:
        - node_modules # NPM packages
      arch: amd64
      dist: focal
      script:
        - python hello_world.py

